# Generated by Django 4.0.4 on 2022-04-26 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shroom_Hunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date of trip')),
                ('location', models.CharField(max_length=100)),
                ('recent_rain', models.CharField(choices=[('U', 'Unknown'), ('C', 'Currently raining'), ('H', 'Rained within last 24 hrs'), ('W', 'Rained within last week'), ('N', 'No recent rain')], default='U', max_length=1)),
                ('mushroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mushroom')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
